### PR TITLE
report errors unrelated to expectations even in case some expectations passed 

### LINKED ISSUE #88: Unclear failure message in case of invalid 'remember' 'bodyPath'
Tests like below are failing without explanation message. 
```
[
  {
    "name": "InvalidRemember",
    "calls": [
      {
        "on": {
          "method": "POST",
          "url": "https://postman-echo.com/post",
          "headers": {
            "Content-Type": "application/json"
          },
          "body": {
            "id": 9
          }
        },
        "expect" : {
          "statusCode": 200
        },
        "remember": {
          "bodyPath": {
            "myVar": "signature"
          }
        }
      }
    ]
  }
]
```
current result
```
unlear.msg
    └ FAILED InvalidRemember [905ms]
        POST https://postman-echo.com/post [902ms]
            √ Status code is 200
```
Workaround: enable debug mode and review debug trace
Suggested solution: add verbose message to report

### PR DESCRIPTION
**Pull request by kajf**
- more clear distinction between error and expectation failure
- trace.Terminated() now only considers failed expectations, not all
should fix #88

### CODE REVIEW

File: types.go [hunk 1]
```diff
@@ -328,7 +328,7 @@ func (trace *CallTrace) addExp(desc string) {
 	trace.ExpDesc[desc] = false
 }
 
-func (trace *CallTrace) addError(err error) {
+func (trace *CallTrace) addFail(err error) {
```
Comment (dpfg) [inline types.go]: A little inconsistent that addFail method accepts error type. addError was more consistent IMO.

Comment (kajf) [reply types.go]: the issue with addError is that method has extra logic related to expectation failure while error is secondary
